import argparse
from typing import Iterable, List, TextIO

import tensorflow.compat.v1 as tf # type: ignore
tf.enable_eager_execution() # type: ignore

# For a .tfrecord file of size N, takes in a file with a list of random
# integers from [0,N), such as generated by
# https://www.random.org/sequences/?mode=advanced and writes out a new file
# shuffled using the random number file as indices specifying an order.

def shuffle(tfrname: str, randname: str) -> None:

    # TODO These type annotations are more or less an experiment. There don't
    # seem to be TF type hints yet, and I don't know how to handle that...

    dataset: Iterable[object] = tf.data.TFRecordDataset(tfrname) # type: ignore
    total_records: int = len([r for r in dataset])
    print(f"Found {total_records} records in source file.")

    randfile: TextIO
    with open(randname, 'r') as randfile:
        total_nums: int = len([int(line) for line in randfile])
        print(f"Found {total_nums} random numbers in random file.")

        if total_records != total_nums:
            raise ValueError("Number of records does not match number of random numbers.")

        outname: str = tfrname + ".shuffled"
        with tf.io.TFRecordWriter(outname) as outfile: # type: ignore
            #TODO This loads the entire source file into memory
            all_records: List[object] = list(dataset)
            randfile.seek(0)
            for num in [int(line) for line in randfile]:
                outfile.write(all_records[num].numpy()) # type: ignore

    print(f'Finished writing shuffled records to file {outname}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Shuffle a .tfrecord file using a random numbers file')
    parser.add_argument('tfrecordfile', metavar='tfrfile', type=str, nargs=1, help='the .tfrecord file to shuffle')
    parser.add_argument('randomfile', metavar='randfile', type=str, nargs=1, help='A file containing '
        'a shuffled sequence of newline-separated numbers from 0 to N-1, where N is the number of records '
        'in the .tfrecord file.'
    )

    args = parser.parse_args()
    shuffle(args.tfrecordfile[0], args.randomfile[0])